package com.yishape.lab.math.codegen;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Generates Rust dispatch code from {@link OpRegistry}.
 *
 * <p>Output files target the {@code graph_ops_dispatch.rs} pattern —
 * Rust projects {@code include!()} the generated file into their existing
 * {@code graph.rs} for forward/backward dispatch match arms.
 *
 * <h2>Generated output</h2>
 * <ul>
 *   <li>{@code SUPPORTED_OPS} — const array of all op tag strings</li>
 *   <li>{@code forward_dispatch()} — match arms routing op → forward function</li>
 *   <li>{@code backward_dispatch()} — match arms routing op → backward function</li>
 * </ul>
 *
 * <h2>Usage</h2>
 * Run {@code CodegenTool} which calls this generator.
 */
public final class RustDispatchGenerator {

    private static final Path PROJECT_ROOT = Paths.get("").toAbsolutePath();
    private static final Path OUTPUT_DIR = PROJECT_ROOT.resolve(
        "target/generated-rust");

    private RustDispatchGenerator() {}

    /** Generates all Rust dispatch files. */
    public static void generate() throws IOException {
        Files.createDirectories(OUTPUT_DIR);

        // GPU dispatch
        generateDispatchFile(true);
        // HPC dispatch
        generateDispatchFile(false);

        System.out.println("  Rust dispatch generated to: " + OUTPUT_DIR);
    }

    private static void generateDispatchFile(boolean gpu) throws IOException {
        String backend = gpu ? "gpu" : "hpc";
        String nameConst = gpu ? "GPU" : "HPC";
        String filename = "graph_ops_dispatch_" + backend + ".rs";
        Path out = OUTPUT_DIR.resolve(filename);

        List<OpDefinition> supportedOps = OpRegistry.ALL_OPS.stream()
            .filter(o -> (gpu ? o.gpu() : o.hpc()) && !o.isLeaf())
            .sorted(Comparator.comparing(OpDefinition::tag))
            .toList();

        StringBuilder sb = new StringBuilder();
        sb.append("// AUTO-GENERATED by com.yishape.lab.math.codegen.RustDispatchGenerator\n");
        sb.append("// Source: OpRegistry (").append(OpRegistry.size()).append(" ops)\n");
        sb.append("// Backend: ").append(nameConst).append("\n");
        sb.append("// Regenerate: mvn exec:java -Dexec.mainClass=\"com.yishape.lab.math.codegen.CodegenTool\"\n\n");

        // SUPPORTED_OPS array
        sb.append("/// All supported op tag strings for this backend.\n");
        sb.append("pub const SUPPORTED_OPS_" + nameConst + ": &[&str] = &[\n");
        for (OpDefinition op : supportedOps) {
            sb.append("    \"").append(op.tag()).append("\",\n");
        }
        sb.append("];\n\n");

        // Compound specials
        Set<String> compound = gpu
            ? OpRegistry.gpuCompoundSpecials() : OpRegistry.hpcCompoundSpecials();
        if (!compound.isEmpty()) {
            sb.append("/// Compound special tags (non-elementwise fused patterns).\n");
            sb.append("pub const COMPOUND_SPECIALS_" + nameConst + ": &[&str] = &[");
            sb.append(compound.stream().map(t -> "\"" + t + "\"").collect(Collectors.joining(", ")));
            sb.append("];\n\n");
        }

        // forward_dispatch match arms
        sb.append("/// Forward dispatch: maps op tag → forward compute function.\n");
        sb.append("pub fn forward_dispatch_" + backend + "(op: &str, inputs: &[&Buffer], output: &mut Buffer, scalar: f64) -> Result<(), GraphError> {\n");
        sb.append("    match op {\n");
        for (OpDefinition op : supportedOps) {
            String fnName = "forward_" + toSnakeCase(op.tag());
            sb.append("        \"").append(op.tag()).append("\" => ").append(fnName).append("(inputs, output, scalar),\n");
        }
        sb.append("        _ => Err(GraphError::UnsupportedOp(op.to_string())),\n");
        sb.append("    }\n");
        sb.append("}\n\n");

        // backward_dispatch match arms
        sb.append("/// Backward dispatch: maps op tag → backward compute function.\n");
        sb.append("pub fn backward_dispatch_" + backend + "(op: &str, grad_out: &Buffer, inputs: &[&Buffer], grads: &mut [Buffer], scalar: f64) -> Result<(), GraphError> {\n");
        sb.append("    match op {\n");
        for (OpDefinition op : supportedOps) {
            String fnName = "backward_" + toSnakeCase(op.tag());
            sb.append("        \"").append(op.tag()).append("\" => ").append(fnName).append("(grad_out, inputs, grads, scalar),\n");
        }
        sb.append("        _ => Err(GraphError::UnsupportedOp(op.to_string())),\n");
        sb.append("    }\n");
        sb.append("}\n");

        Files.writeString(out, sb.toString());
    }

    /** Converts camelCase op tag to snake_case function name. */
    private static String toSnakeCase(String camelCase) {
        return camelCase.replaceAll("([a-z])([A-Z])", "$1_$2").toLowerCase();
    }
}
