package com.yishape.lab.math.bench;

import java.io.*;
import java.nio.file.*;
import java.util.*;

import com.yishape.lab.math.compute.hpc.HpcConfig;
import com.yishape.lab.math.compute.hpc.HpcSwitch;
import com.yishape.lab.math.hpc.*;
import com.yishape.lab.math.linalg.*;

/**
 * Cross-validates Java (Pure / HPC API / HPC Direct) against NumPy reference results.
 * Reads test matrices from benchmarks/out/cross_validate/ (generated by cross_validate.py).
 */
public class CrossValidateNumpy {

    static final Path DATA_DIR = Path.of("benchmarks/out/cross_validate");
    static final double EPS = 1e-12;

    record Diff(String op, String size, String backend, String metric,
                double numpyVal, double javaVal, double absDiff, double relDiff) {}

    public static void main(String[] args) throws Exception {
        List<Diff> diffs = new ArrayList<>();
        System.out.println("=== Java vs NumPy Cross-Validation ===\n");

        validateGemm(diffs);
        validateSvd(diffs);
        validateQr(diffs);
        validateCholesky(diffs);
        validateLu(diffs);
        validateSolve(diffs);
        validateInverse(diffs);
        validateEigenSymmetric(diffs);
        validateEigenGeneral(diffs);

        printSummary(diffs);
    }

    static void printSummary(List<Diff> diffs) {
        System.out.println("\n=== Summary ===");
        long fails = 0;
        for (Diff d : diffs) {
            boolean bad = d.absDiff > EPS && d.relDiff > EPS;
            if (bad) fails++;
            System.out.printf("%s %-20s %-15s %-18s | numpy=% .8e java=% .8e | abs=% .1e rel=% .1e%s%n",
                d.op, d.size, d.backend, d.metric,
                d.numpyVal, d.javaVal, d.absDiff, d.relDiff,
                bad ? " ***" : "");
        }
        System.out.printf("%nPrecision failures (abs>%e && rel>%e): %d / %d%n", EPS, EPS, fails, diffs.size());
        if (fails > 0) {
            System.out.println("\n*** WARNING: Numerical differences vs NumPy detected! ***");
            System.exit(1);
        } else {
            System.out.println("All Java backends produce results consistent with NumPy reference.");
        }
    }

    // ---- I/O helpers ----

    static double[][] readMatrix(String fn) throws IOException {
        List<String> lines = Files.readAllLines(DATA_DIR.resolve(fn));
        String[] h = lines.get(0).trim().split("\\s+");
        int m = Integer.parseInt(h[0]), n = Integer.parseInt(h[1]);
        double[][] a = new double[m][n];
        for (int i = 0; i < m; i++) {
            String[] v = lines.get(i + 1).trim().split("\\s+");
            for (int j = 0; j < n; j++) a[i][j] = Double.parseDouble(v[j]);
        }
        return a;
    }

    static double[] readVector(String fn) throws IOException {
        List<String> lines = Files.readAllLines(DATA_DIR.resolve(fn));
        int n = Integer.parseInt(lines.get(0).trim());
        double[] v = new double[n];
        String[] vals = lines.get(1).trim().split("\\s+");
        for (int i = 0; i < n; i++) v[i] = Double.parseDouble(vals[i]);
        return v;
    }

    // ---- Metric helpers ----

    static double cs(double[] v) { double s = 0; for (double x : v) s += x; return s; }
    static double cs(double[][] m) { double s = 0; for (double[] r : m) for (double x : r) s += x; return s; }

    static double frob(double[][] m) {
        double s = 0; for (double[] r : m) for (double x : r) s += x * x; return Math.sqrt(s);
    }

    static double[] sortedCopy(double[] v) { double[] c = Arrays.copyOf(v, v.length); Arrays.sort(c); return c; }

    static void compare(List<Diff> d, String o, String s, String b, String m, double np, double jv) {
        double ad = Math.abs(np - jv);
        double dn = Math.max(Math.abs(np), Math.abs(jv));
        double rd = dn > 1e-15 ? ad / dn : ad;
        d.add(new Diff(o, s, b, m, np, jv, ad, rd));
    }

    static void setHpcApiMode(boolean enable) {
        if (enable) HpcSwitch.enable(); else HpcSwitch.disable();
        System.setProperty(HpcConfig.PROP_ENABLE, Boolean.toString(enable));
        if (enable) {
            System.setProperty(HpcConfig.PROP_GEMM_MIN_FLOPS, "0");
            System.setProperty(HpcConfig.PROP_CHOLESKY_MIN_DIM, "32");
            System.setProperty(HpcConfig.PROP_SVD_MIN_TOTAL_ELEMENTS, "1");
            System.setProperty(HpcConfig.PROP_SOLVE_MIN_DIM, "32");
            System.setProperty(HpcConfig.PROP_LU_MIN_DIM, "32");
            System.setProperty(HpcConfig.PROP_EIGEN_MIN_DIM, "32");
            System.setProperty(HpcConfig.PROP_EIGEN_NONSYMMETRIC_MIN_DIM, "32");
        }
    }

    static IMatrix<Double> toIM(double[][] m) { return Linalg.matrix(m); }
    static IVector<Double> toIV(double[] v) { return Linalg.vector(v); }

    static double[][] toArr2D(IMatrix<Double> m) {
        double[][] a = new double[m.rows()][m.cols()];
        for (int i = 0; i < m.rows(); i++) for (int j = 0; j < m.cols(); j++) a[i][j] = m.get(i, j);
        return a;
    }

    static double[] toArr1D(IVector<Double> v) {
        double[] a = new double[v.size()];
        for (int i = 0; i < v.size(); i++) a[i] = v.get(i);
        return a;
    }

    // ---- Validation methods ----

    static void validateGemm(List<Diff> diffs) throws Exception {
        System.out.println("--- GEMM ---");
        for (int n : new int[]{50, 100, 200}) {
            double[][] A = readMatrix(String.format("gemm_A_%d.txt", n));
            double[][] B = readMatrix(String.format("gemm_B_%d.txt", n));
            double[][] Cnp = readMatrix(String.format("gemm_C_numpy_%d.txt", n));
            double csNp = cs(Cnp);
            String sz = n + "x" + n;

            // Pure Java
            HpcSwitch.disable();
            IMatrix<Double> Cj = toIM(A).mmul(toIM(B));
            double csPure = cs(toArr2D(Cj));
            compare(diffs, "GEMM", sz, "java_pure", "C_checksum", csNp, csPure);
            System.out.printf("  %s pure:  cs=% .8e (np=% .8e) diff=%.1e%n", sz, csPure, csNp, Math.abs(csNp - csPure));

            // HPC API
            setHpcApiMode(true);
            IMatrix<Double> Capi = toIM(A).mmul(toIM(B));
            compare(diffs, "GEMM", sz, "java_hpc_api", "C_checksum", csNp, cs(toArr2D(Capi)));

            // HPC Direct
            double[][] Cd = YishapeHpc.tryMatMul(A, B);
            compare(diffs, "GEMM", sz, "java_hpc_direct", "C_checksum", csNp, cs(Cd));
        }
    }

    static void validateSvd(List<Diff> diffs) throws Exception {
        System.out.println("--- SVD ---");
        for (int n : new int[]{50, 100}) {
            double[][] A = readMatrix(String.format("svd_A_%d.txt", n));
            double[] sNp = readVector(String.format("svd_s_numpy_%d.txt", n));
            double csNp = cs(sNp);
            String sz = n + "x" + n;

            // Pure Java
            HpcSwitch.disable();
            double[] sJ = toArr1D(toIM(A).svd()._2);
            compare(diffs, "SVD", sz, "java_pure", "s_checksum", csNp, cs(sJ));
            System.out.printf("  %s pure:  s_cs=% .8e (np=% .8e) diff=%.1e%n", sz, cs(sJ), csNp, Math.abs(csNp - cs(sJ)));

            // HPC API
            setHpcApiMode(true);
            double[] sApi = toArr1D(toIM(A).svd()._2);
            compare(diffs, "SVD", sz, "java_hpc_api", "s_checksum", csNp, cs(sApi));

            // HPC Direct
            SvdResult r = YishapeHpc.svd(A);
            compare(diffs, "SVD", sz, "java_hpc_direct", "s_checksum", csNp, cs(r.singularValues()));
        }
    }

    static void validateQr(List<Diff> diffs) throws Exception {
        System.out.println("--- QR ---");
        for (int n : new int[]{50, 100}) {
            double[][] A = readMatrix(String.format("qr_A_%d.txt", n));
            double[][] Qnp = readMatrix(String.format("qr_Q_numpy_%d.txt", n));
            double[][] Rnp = readMatrix(String.format("qr_R_numpy_%d.txt", n));
            double csRnp = cs(Rnp);
            String sz = n + "x" + n;

            // Pure Java
            HpcSwitch.disable();
            var qrJ = toIM(A).qr();
            double csRj = cs(toArr2D(qrJ._2));
            compare(diffs, "QR", sz, "java_pure", "R_checksum", csRnp, csRj);
            System.out.printf("  %s pure:  R_cs=% .8e (np=% .8e) diff=%.1e%n", sz, csRj, csRnp, Math.abs(csRnp - csRj));

            // HPC API
            setHpcApiMode(true);
            var qrApi = toIM(A).qr();
            compare(diffs, "QR", sz, "java_hpc_api", "R_checksum", csRnp, cs(toArr2D(qrApi._2)));

            // HPC Direct
            QrResult r = YishapeHpc.qr(A);
            compare(diffs, "QR", sz, "java_hpc_direct", "R_checksum", csRnp, cs(r.r()));
        }
    }

    static void validateCholesky(List<Diff> diffs) throws Exception {
        System.out.println("--- Cholesky ---");
        for (int n : new int[]{50, 100}) {
            double[][] A = readMatrix(String.format("cholesky_A_%d.txt", n));
            double[][] Lnp = readMatrix(String.format("cholesky_L_numpy_%d.txt", n));
            double csLnp = cs(Lnp);
            String sz = n + "x" + n;

            // Pure Java
            HpcSwitch.disable();
            var cJ = toIM(A).cholesky();
            double csLj = cs(toArr2D(cJ));
            compare(diffs, "Cholesky", sz, "java_pure", "L_checksum", csLnp, csLj);
            System.out.printf("  %s pure:  L_cs=% .8e (np=% .8e) diff=%.1e%n", sz, csLj, csLnp, Math.abs(csLnp - csLj));

            // HPC API
            setHpcApiMode(true);
            var cApi = toIM(A).cholesky();
            compare(diffs, "Cholesky", sz, "java_hpc_api", "L_checksum", csLnp, cs(toArr2D(cApi)));

            // HPC Direct
            CholeskyResult r = YishapeHpc.cholesky(A);
            compare(diffs, "Cholesky", sz, "java_hpc_direct", "L_checksum", csLnp, cs(r.lLower()));
        }
    }

    static void validateLu(List<Diff> diffs) throws Exception {
        System.out.println("--- LU ---");
        for (int n : new int[]{50, 100}) {
            double[][] A = readMatrix(String.format("lu_A_%d.txt", n));
            double[][] Lnp = readMatrix(String.format("lu_L_numpy_%d.txt", n));
            double[][] Unp = readMatrix(String.format("lu_U_numpy_%d.txt", n));
            double csLnp = cs(Lnp), csUnp = cs(Unp);
            String sz = n + "x" + n;

            // Pure Java
            HpcSwitch.disable();
            var luJ = toIM(A).lu();
            compare(diffs, "LU", sz, "java_pure", "L_checksum", csLnp, cs(toArr2D(luJ._1)));
            compare(diffs, "LU", sz, "java_pure", "U_checksum", csUnp, cs(toArr2D(luJ._2)));
            System.out.printf("  %s pure:  L_cs=% .8e (np=% .8e) U_cs=% .8e (np=% .8e)%n",
                sz, cs(toArr2D(luJ._1)), csLnp, cs(toArr2D(luJ._2)), csUnp);

            // HPC API
            setHpcApiMode(true);
            var luApi = toIM(A).lu();
            compare(diffs, "LU", sz, "java_hpc_api", "L_checksum", csLnp, cs(toArr2D(luApi._1)));
            compare(diffs, "LU", sz, "java_hpc_api", "U_checksum", csUnp, cs(toArr2D(luApi._2)));

            // HPC Direct
            LuResult r = YishapeHpc.lu(A);
            compare(diffs, "LU", sz, "java_hpc_direct", "L_checksum", csLnp, cs(r.l()));
            compare(diffs, "LU", sz, "java_hpc_direct", "U_checksum", csUnp, cs(r.u()));
        }
    }

    static void validateSolve(List<Diff> diffs) throws Exception {
        System.out.println("--- Solve ---");
        for (int n : new int[]{50, 100}) {
            double[][] A = readMatrix(String.format("solve_A_%d.txt", n));
            double[] b = readVector(String.format("solve_b_%d.txt", n));
            double[] xNp = readVector(String.format("solve_x_numpy_%d.txt", n));
            double csNp = cs(xNp);
            String sz = "n=" + n;

            // Pure Java
            HpcSwitch.disable();
            double[] xJ = toArr1D(toIM(A).solve(toIV(b)));
            compare(diffs, "Solve", sz, "java_pure", "x_checksum", csNp, cs(xJ));
            System.out.printf("  %s pure:  x_cs=% .8e (np=% .8e) diff=%.1e%n", sz, cs(xJ), csNp, Math.abs(csNp - cs(xJ)));

            // HPC API
            setHpcApiMode(true);
            double[] xApi = toArr1D(toIM(A).solve(toIV(b)));
            compare(diffs, "Solve", sz, "java_hpc_api", "x_checksum", csNp, cs(xApi));

            // HPC Direct
            DenseSolveResult r = YishapeHpc.solveSquare(A, b);
            compare(diffs, "Solve", sz, "java_hpc_direct", "x_checksum", csNp, cs(r.x()));
        }
    }

    static void validateInverse(List<Diff> diffs) throws Exception {
        System.out.println("--- Inverse ---");
        for (int n : new int[]{50, 100}) {
            double[][] A = readMatrix(String.format("inverse_A_%d.txt", n));
            double[][] AinvNp = readMatrix(String.format("inverse_Ainv_numpy_%d.txt", n));
            double csNp = cs(AinvNp);
            String sz = n + "x" + n;

            // Pure Java
            HpcSwitch.disable();
            double[][] AinvJ = toArr2D(toIM(A).inv());
            compare(diffs, "Inverse", sz, "java_pure", "Ainv_checksum", csNp, cs(AinvJ));
            System.out.printf("  %s pure:  Ainv_cs=% .8e (np=% .8e) diff=%.1e%n", sz, cs(AinvJ), csNp, Math.abs(csNp - cs(AinvJ)));

            // HPC API
            setHpcApiMode(true);
            double[][] AinvApi = toArr2D(toIM(A).inv());
            compare(diffs, "Inverse", sz, "java_hpc_api", "Ainv_checksum", csNp, cs(AinvApi));

            // HPC Direct
            InverseResult r = YishapeHpc.inverse(A);
            compare(diffs, "Inverse", sz, "java_hpc_direct", "Ainv_checksum", csNp, cs(r.inv()));
        }
    }

    static void validateEigenSymmetric(List<Diff> diffs) throws Exception {
        System.out.println("--- Eigen Symmetric ---");
        for (int n : new int[]{50, 100}) {
            double[][] A = readMatrix(String.format("eigsym_A_%d.txt", n));
            double[] evalsNp = readVector(String.format("eigsym_evals_numpy_%d.txt", n));
            double csNp = cs(evalsNp);
            String sz = n + "x" + n;

            // Pure Java (returns descending; sort to match NumPy's ascending)
            HpcSwitch.disable();
            var eJ = toIM(A).eigen();
            double csJ = cs(sortedCopy(toArr1D(eJ._1)));
            compare(diffs, "EigenSym", sz, "java_pure", "evals_sum", csNp, csJ);
            System.out.printf("  %s pure:  evals_sum(sorted)=% .8e (np=% .8e) diff=%.1e%n", sz, csJ, csNp, Math.abs(csNp - csJ));

            // HPC API
            setHpcApiMode(true);
            var eApi = toIM(A).eigen();
            compare(diffs, "EigenSym", sz, "java_hpc_api", "evals_sum", csNp, cs(sortedCopy(toArr1D(eApi._1))));

            // HPC Direct (faer returns ascending, matching NumPy)
            SymmetricEigenResult r = YishapeHpc.eigenSymmetric(A);
            compare(diffs, "EigenSym", sz, "java_hpc_direct", "evals_sum", csNp, cs(r.eigenvaluesAscending()));
        }
    }

    static void validateEigenGeneral(List<Diff> diffs) throws Exception {
        System.out.println("--- Eigen General ---");
        for (int n : new int[]{50, 100}) {
            double[][] A = readMatrix(String.format("eiggen_A_%d.txt", n));
            double[] evalsRealNp = readVector(String.format("eiggen_evals_real_numpy_%d.txt", n));
            double csNp = cs(evalsRealNp);
            String sz = n + "x" + n;

            // Pure Java
            HpcSwitch.disable();
            var eJ = toIM(A).eigen();
            compare(diffs, "EigenGen", sz, "java_pure", "evals_real_sum", csNp, cs(toArr1D(eJ._1)));
            System.out.printf("  %s pure:  evals_real_sum=% .8e (np=% .8e) diff=%.1e%n", sz, cs(toArr1D(eJ._1)), csNp, Math.abs(csNp - cs(toArr1D(eJ._1))));

            // HPC API
            setHpcApiMode(true);
            var eApi = toIM(A).eigen();
            compare(diffs, "EigenGen", sz, "java_hpc_api", "evals_real_sum", csNp, cs(toArr1D(eApi._1)));

            // HPC Direct
            NonsymmetricEigenResult r = YishapeHpc.eigenNonsymmetric(A);
            compare(diffs, "EigenGen", sz, "java_hpc_direct", "evals_real_sum", csNp, cs(r.eigenvaluesReal()));
        }
    }
}
