#!/usr/bin/env python3
"""通篇检查英文术语/缩写使用规范"""
import re, os
from collections import defaultdict

BASE = '/home/reremouse/work/yishape-math/book/'

# 常见英文缩写（需要首次完整介绍）
ABBR_TRACK = {}  # abbr -> (full_name, introduced_in_section)

# 按章节扫描
CHAPTER_ORDER = [
    ('Chapter1_LinearAlgebra', [
        '1.1.Vector.md', '1.2.Matrix.md', '1.3.Matrix decomposition.md',
        '1.4.Linear Equation System.md', '1.5.Applications.md',
        '1.6.Numerical stability.md', '1.7.Summary.md', 'introduction.md'
    ]),
    ('Chapter2_DataFrame', ['2.1.md', '2.2.md', '2.3.md', '2.4.md', '2.5.md', 'introduction.md', 'summary.md']),
    ('Chapter3_Visualization', ['3.1.md', '3.2.md', '3.3.md', '3.4.md', '3.5.md', 'introduction.md', 'summary.md']),
    ('Chapter4_Statistics', [
        '4.1.md', '4.2.md', '4.3.md', '4.4.md', '4.5.md', '4.6.md', '4.7.md',
        'introduction.md', 'summary.md'
    ]),
    ('Chapter5_Machine_learning', [
        '5.1. Regression.md', '5.2. Classification.md', '5.3. Clustering.md',
        '5.4. Dimension reduction.md', '5.5. Tree ensembles and boosting.md',
        'introduction.md', 'summary.md'
    ]),
    ('Chapter6_Optimization', [
        '6.1. Optimization.md', '6.2. Linear programming.md',
        '6.3. Integer programming.md', '6.4. Nonconvex optimization.md',
        'introduction.md', 'summary.md'
    ]),
    ('Chapter7_Time_series_and_signal_processing', [
        '7.1. Time series.md', '7.2. signal processing.md',
        '7.3. audio processing.md', '7.4. Music mining.md',
        'introduction.md', 'summary.md'
    ]),
]

# 常见缩写及其全称（用于检查是否首次出现时有完整介绍）
KNOWN_ABBR = {
    'AI': 'Artificial Intelligence',
    'ML': 'Machine Learning',
    'DL': 'Deep Learning',
    'NLP': 'Natural Language Processing',
    'CV': 'Computer Vision',
    'RL': 'Reinforcement Learning',
    'SVM': 'Support Vector Machine',
    'KNN': 'K-Nearest Neighbors',
    'K-means': 'K-Means Clustering',
    'GMM': 'Gaussian Mixture Model',
    'DBSCAN': 'Density-Based Spatial Clustering of Applications with Noise',
    'PCA': 'Principal Component Analysis',
    'LDA': 'Linear Discriminant Analysis',
    'ANOVA': 'Analysis of Variance',
    'ARIMA': 'Autoregressive Integrated Moving Average',
    'AR': 'Autoregressive',
    'MA': 'Moving Average',
    'ARMA': 'Autoregressive Moving Average',
    'LP': 'Linear Programming',
    'IP': 'Integer Programming',
    'MILP': 'Mixed Integer Linear Programming',
    'QP': 'Quadratic Programming',
    'NLP_': 'Nonlinear Programming',  # suffix _ to avoid matching NLP
    'FFT': 'Fast Fourier Transform',
    'DFT': 'Discrete Fourier Transform',
    'STFT': 'Short-Time Fourier Transform',
    'MFCC': 'Mel-Frequency Cepstral Coefficient',
    'IF': 'Instantaneous Frequency',
    'CNN': 'Convolutional Neural Network',
    'RNN': 'Recurrent Neural Network',
    'LSTM': 'Long Short-Term Memory',
    'GRU': 'Gated Recurrent Unit',
    'GAN': 'Generative Adversarial Network',
    'VAE': 'Variational Autoencoder',
    'AE': 'Autoencoder',
    'MLP': 'Multilayer Perceptron',
    'ReLU': 'Rectified Linear Unit',
    'ELU': 'Exponential Linear Unit',
    'SGD': 'Stochastic Gradient Descent',
    'Adam': 'Adaptive Moment Estimation',
    'RMSProp': 'Root Mean Square Propagation',
    'Dropout': None,  # just the term
    'BatchNorm': 'Batch Normalization',
    'BN': 'Batch Normalization',
    'AUC': 'Area Under Curve',
    'ROC': 'Receiver Operating Characteristic',
    'PR': 'Precision-Recall',
    'IoU': 'Intersection over Union',
    'mAP': 'mean Average Precision',
    'F1': 'F1-Score',
    'MAE': 'Mean Absolute Error',
    'MSE': 'Mean Squared Error',
    'RMSE': 'Root Mean Square Error',
    'MAPE': 'Mean Absolute Percentage Error',
    'R²': 'R-squared / Coefficient of Determination',
    'RSS': 'Residual Sum of Squares',
    'TSS': 'Total Sum of Squares',
    'SSR': 'Sum of Squares Regression',
    'SSE': 'Sum of Squares Error',
    'LR': 'Linear Regression',
    'GLM': 'Generalized Linear Model',
    'GLS': 'Generalized Least Squares',
    'WLS': 'Weighted Least Squares',
    'OLS': 'Ordinary Least Squares',
    'MLE': 'Maximum Likelihood Estimation',
    'MAP': 'Maximum A Posteriori',
    'EM': 'Expectation-Maximization',
    'KL': 'Kullback-Leibler (Divergence)',
    'HMM': 'Hidden Markov Model',
    'CRF': 'Conditional Random Field',
    'NB': 'Naive Bayes',
    'DT': 'Decision Tree',
    'RF': 'Random Forest',
    'GBDT': 'Gradient Boosting Decision Tree',
    'XGBoost': 'eXtreme Gradient Boosting',
    'LightGBM': 'Light Gradient Boosting Machine',
    'CatBoost': 'Categorical Boosting',
    'AdaBoost': 'Adaptive Boosting',
    'Bagging': 'Bootstrap Aggregating',
    'Boosting': None,  # just term
    'Stacking': 'Stacked Generalization',
    'CrossVal': 'Cross-Validation',
    'CV': 'Cross-Validation',
    'K-Fold': 'K-Fold Cross-Validation',
    'LOO': 'Leave-One-Out',
    'LOO-CV': 'Leave-One-Out Cross-Validation',
    'BIC': 'Bayesian Information Criterion',
    'AIC': 'Akaike Information Criterion',
    'L-BFGS': "Limited-memory Broyden-Fletcher-Goldfarb-Shanno",
    'BFGS': 'Broyden-Fletcher-Goldfarb-Shanno',
    'SMO': 'Sequential Minimal Optimization',
    'SVD': 'Singular Value Decomposition',
    'LU': 'Lower-Upper (Decomposition)',
    'LDL': 'Lower-Diagonal-Lower (Decomposition)',
    'QR': 'Q-Decorrelation-R (Decomposition)',
    'Cholesky': 'Cholesky Decomposition',
    'EVD': 'Eigenvalue Decomposition',
    'QRp': 'QR Decomposition',
    'IFT': 'Inverse Fourier Transform',
    'DFA': 'Detrended Fluctuation Analysis',
    'Hurst': 'Hurst Exponent',
    'PSD': 'Power Spectral Density',
    'SNR': 'Signal-to-Noise Ratio',
    'ISI': 'Intersymbol Interference',
    'FIR': 'Finite Impulse Response',
    'IIR': 'Infinite Impulse Response',
    'AM': 'Amplitude Modulation',
    'FM': 'Frequency Modulation',
    'QAM': 'Quadrature Amplitude Modulation',
    'PCM': 'Pulse Code Modulation',
    'ADC': 'Analog-to-Digital Converter',
    'DAC': 'Digital-to-Analog Converter',
    'RPM': 'Revolutions Per Minute',
    'BPM': 'Beats Per Minute',
    'Hz': 'Hertz',
    'kHz': 'Kilohertz',
    'dB': 'Decibel',
    'dBm': 'Decibel-milliwatt',
    'FFT': 'Fast Fourier Transform',
    'STFT': 'Short-Time Fourier Transform',
    'CWT': 'Continuous Wavelet Transform',
    'DWT': 'Discrete Wavelet Transform',
    'IMF': 'Intrinsic Mode Function',
    'EMD': 'Empirical Mode Decomposition',
    'HHT': 'Hilbert-Huang Transform',
    'HT': 'Hilbert Transform',
    'Hilbert': 'Hilbert Transform',
    'ACE': 'Automatic Chord Estimation',
    'MIR': 'Music Information Retrieval',
    'MIDI': 'Musical Instrument Digital Interface',
    'MP3': 'MPEG-1 Audio Layer III',
    'WAV': 'Waveform Audio File',
    'FLAC': 'Free Lossless Audio Codec',
    'Ogg': 'Ogg Vorbis',
    'BPF': 'Band-Pass Filter',
    'LPF': 'Low-Pass Filter',
    'HPF': 'High-Pass Filter',
    'BPF': 'Band-Pass Filter',
    'API': 'Application Programming Interface',
    'CLI': 'Command Line Interface',
    'GUI': 'Graphical User Interface',
    'IDE': 'Integrated Development Environment',
    'CPU': 'Central Processing Unit',
    'GPU': 'Graphics Processing Unit',
    'TPU': 'Tensor Processing Unit',
    'FPGA': 'Field-Programmable Gate Array',
    'ASIC': 'Application-Specific Integrated Circuit',
    'RAM': 'Random Access Memory',
    'ROM': 'Read-Only Memory',
    'SSD': 'Solid State Drive',
    'HDD': 'Hard Disk Drive',
    'USB': 'Universal Serial Bus',
    'TCP': 'Transmission Control Protocol',
    'IP': 'Internet Protocol',
    'HTTP': 'Hypertext Transfer Protocol',
    'HTTPS': 'HTTP Secure',
    'FTP': 'File Transfer Protocol',
    'SSH': 'Secure Shell',
    'TLS': 'Transport Layer Security',
    'SSL': 'Secure Sockets Layer',
    'DNS': 'Domain Name System',
    'RAID': 'Redundant Array of Independent Disks',
    'NAS': 'Network Attached Storage',
    'SAN': 'Storage Area Network',
    'VM': 'Virtual Machine',
    'Docker': None,  # just term
    'K8s': 'Kubernetes',
    'ETL': 'Extract-Transform-Load',
    'ELT': 'Extract-Load-Transform',
    'REST': 'Representational State Transfer',
    'SOA': 'Service-Oriented Architecture',
    'Microservice': 'Microservice Architecture',
    'CI': 'Continuous Integration',
    'CD': 'Continuous Deployment',
    'DevOps': 'Development Operations',
    'Agile': 'Agile Development',
    'Scrum': None,
    'Kanban': None,
    'JIRA': None,
    'Git': None,
    'SVN': 'Apache Subversion',
    'Mercurial': None,
    'Markdown': None,
    'LaTeX': None,
    'PDF': 'Portable Document Format',
    'HTML': 'HyperText Markup Language',
    'CSS': 'Cascading Style Sheets',
    'JS': 'JavaScript',
    'JSON': 'JavaScript Object Notation',
    'XML': 'Extensible Markup Language',
    'YAML': "YAML Ain't Markup Language",
    'TOML': "Tom's Obvious, Minimal Language",
    'CSV': 'Comma-Separated Values',
    'TSV': 'Tab-Separated Values',
    'SQL': 'Structured Query Language',
    'NoSQL': 'Not Only SQL',
    'ORM': 'Object-Relational Mapping',
    'ACID': 'Atomicity, Consistency, Isolation, Durability',
    'CAP': 'Consistency, Availability, Partition Tolerance',
    'BASE': 'Basically Available, Soft State, Eventually Consistent',
    'OLTP': 'Online Transaction Processing',
    'OLAP': 'Online Analytical Processing',
    'DW': 'Data Warehouse',
    'DM': 'Data Mart',
    'ODS': 'Operational Data Store',
    'EDW': 'Enterprise Data Warehouse',
    'BI': 'Business Intelligence',
    'Einstein': "Salesforce Einstein",
    'Spark': 'Apache Spark',
    'Hadoop': 'Apache Hadoop',
    'Kafka': 'Apache Kafka',
    'Flink': 'Apache Flink',
    'Storm': 'Apache Storm',
    'Beam': 'Apache Beam',
    'Airflow': 'Apache Airflow',
    'Dag': 'Directed Acyclic Graph',
    'TensorFlow': None,
    'PyTorch': None,
    'Keras': None,
    'Caffe': 'Convolutional Architecture for Fast Feature Embedding',
    'MXNet': 'Mixed eXecutable Net',
    'JAX': 'Just After eXecution',
    'Scikit-learn': 'scikit-learn',
    'Sklearn': 'scikit-learn',
    'NLTK': 'Natural Language Toolkit',
    'SpaCy': None,
    'Gensim': None,
    'OpenCV': 'Open Computer Vision',
    'OpenMA': 'Open Motion Analysis',
    'SciPy': 'Scientific Python',
    'NumPy': 'Numerical Python',
    'Pandas': 'Python Data Analysis Library',
    'Matplotlib': None,
    'Seaborn': None,
    'Plotly': None,
    'Bokeh': None,
    'Altair': None,
    'Vega': None,
    'Vega-Lite': None,
    'Tableau': None,
    'PowerBI': 'Microsoft Power BI',
    'FineReport': 'FanRuan FineReport',
    'ECharts': 'Enterprise Charts',
    'AntV': 'Ant Visualization',
    'D3': 'Data-Driven Documents',
    'Three.js': None,
    'WebGL': 'Web Graphics Library',
    'SVG': 'Scalable Vector Graphics',
    'CAN': 'Controller Area Network',
    'LIN': 'Local Interconnect Network',
    'FlexRay': None,
    'MOST': 'Media Oriented Systems Transport',
    'AutoSAR': 'AUTOSAR (Automotive Open System Architecture)',
    'OBD': 'On-Board Diagnostics',
    'OBD-II': 'On-Board Diagnostics Generation II',
    'ECU': 'Electronic Control Unit',
    'EMS': 'Engine Management System',
    'TCU': 'Transmission Control Unit',
    'ABS': 'Anti-lock Braking System',
    'ESC': 'Electronic Stability Control',
    'ACC': 'Adaptive Cruise Control',
    'LKA': 'Lane Keeping Assist',
    'AEB': 'Autonomous Emergency Braking',
    'BSD': 'Blind Spot Detection',
    'FCW': 'Forward Collision Warning',
    'LDW': 'Lane Departure Warning',
    'PCW': 'Pedestrian Collision Warning',
    'TSR': 'Traffic Sign Recognition',
    'ISA': 'Intelligent Speed Adaptation',
    'V2X': 'Vehicle-to-Everything',
    'V2V': 'Vehicle-to-Vehicle',
    'V2I': 'Vehicle-to-Infrastructure',
    'V2P': 'Vehicle-to-Pedestrian',
    'V2N': 'Vehicle-to-Network',
    'DSRC': 'Dedicated Short-Range Communications',
    'C-V2X': 'Cellular V2X',
    '5G': 'Fifth Generation Mobile Networks',
    'LTE': 'Long Term Evolution',
    'GNSS': 'Global Navigation Satellite System',
    'GPS': 'Global Positioning System',
    'GLONASS': 'Global Navigation Satellite System (Russia)',
    'Galileo': 'Galileo Navigation Satellite System (EU)',
    'BeiDou': 'BeiDou Navigation Satellite System (China)',
    'IMU': 'Inertial Measurement Unit',
    'INS': 'Inertial Navigation System',
    'LiDAR': 'Light Detection and Ranging',
    'RADAR': 'Radio Detection and Ranging',
    'Camera': 'Camera (Vision Sensor)',
    'Odometry': None,
    'SLAM': 'Simultaneous Localization and Mapping',
    'EKF': 'Extended Kalman Filter',
    'UKF': 'Unscented Kalman Filter',
    'PF': 'Particle Filter',
    'ESKF': 'Error-State Kalman Filter',
    'MSCKF': 'Multi-State Constraint Kalman Filter',
    'VI-SLAM': 'Visual-Inertial SLAM',
    'VO': 'Visual Odometry',
    'IO': 'Inertial Odometry',
    'SfM': 'Structure from Motion',
    'MVS': 'Multi-View Stereo',
    'NeRF': 'Neural Radiance Fields',
    'Gaussian': 'Gaussian Splatting',
    'OCR': 'Optical Character Recognition',
    'ICR': 'Intelligent Character Recognition',
    'OMR': 'Optical Mark Recognition',
    'MRZ': 'Machine Readable Zone',
    'NFC': 'Near-Field Communication',
    'RFID': 'Radio-Frequency Identification',
    'BLE': 'Bluetooth Low Energy',
    'Wi-Fi': 'Wireless Fidelity',
    'UWB': 'Ultra-Wideband',
    'ZigBee': None,
    'Thread': None,
    'Matter': None,
    'LoRa': 'Long Range',
    'SigFox': None,
    'NB-IoT': 'Narrowband IoT',
    'MQTT': 'Message Queuing Telemetry Transport',
    'CoAP': 'Constrained Application Protocol',
    'AMQP': 'Advanced Message Queuing Protocol',
    'HTTP/2': 'HTTP Version 2',
    'HTTP/3': 'HTTP Version 3',
    'gRPC': 'Google Remote Procedure Call',
    'Thrift': 'Apache Thrift',
    'GraphQL': None,
    'WebSocket': None,
    'WebRTC': 'Web Real-Time Communication',
    'ICE': 'Interactive Connectivity Establishment',
    'STUN': 'Session Traversal Utilities for NAT',
    'TURN': 'Traversal Using Relays around NAT',
    'SIP': 'Session Initiation Protocol',
    'RTP': 'Real-time Transport Protocol',
    'RTSP': 'Real Time Streaming Protocol',
    'RTMP': 'Real-Time Messaging Protocol',
    'HLS': 'HTTP Live Streaming',
    'DASH': 'Dynamic Adaptive Streaming over HTTP',
    'MPEG': 'Moving Picture Experts Group',
    'H.264': 'H.264/AVC',
    'H.265': 'H.265/HEVC',
    'AV1': 'AOMedia Video 1',
    'VP8': 'Video Processor 8',
    'VP9': 'Video Processor 9',
    'Opus': None,
    'AAC': 'Advanced Audio Coding',
    'OGG': 'Ogg (container format)',
    'FLAC': 'Free Lossless Audio Codec',
    'APE': "Monkey's Audio",
    'ALAC': 'Apple Lossless Audio Codec',
    'ID3': 'ID3 Tag (MP3 metadata)',
    'Vorbis': None,
    'Theora': None,
    'WebM': None,
    'Matroska': None,
    'MKV': 'Matroska Video',
    'MP4': 'MPEG-4 Part 14',
    'M4A': 'MPEG-4 Audio',
    'M4V': 'MPEG-4 Video',
    'MOV': 'QuickTime Movie',
    'AVI': 'Audio Video Interleave',
    'WMV': 'Windows Media Video',
    'FLV': 'Flash Video',
    'SWF': 'Small Web Format / Flash',
    'M3U8': 'HTTP Live Streaming Playlist',
    'M3U': 'MP3 URL (playlist format)',
    'PLS': 'Playlist',
    'AES': 'Advanced Encryption Standard',
    'DES': 'Data Encryption Standard',
    '3DES': 'Triple DES',
    'RSA': 'Rivest-Shamir-Adleman',
    'ECC': 'Elliptic Curve Cryptography',
    'DH': 'Diffie-Hellman',
    'DSA': 'Digital Signature Algorithm',
    'ECDSA': 'Elliptic Curve DSA',
    'EdDSA': 'Edwards-curve DSA',
    'MD5': 'Message-Digest Algorithm 5',
    'SHA-1': 'Secure Hash Algorithm 1',
    'SHA-2': 'Secure Hash Algorithm 2',
    'SHA-3': 'Secure Hash Algorithm 3',
    'BLAKE2': None,
    'Argon2': None,
    'bcrypt': None,
    'scrypt': None,
    'PBKDF2': 'Password-Based Key Derivation Function 2',
    'HKDF': 'HMAC-based Extract-and-Expand Key Derivation Function',
    'HMAC': 'Hash-based Message Authentication Code',
    'TLS': 'Transport Layer Security',
    'SSH': 'Secure Shell',
    'PGP': 'Pretty Good Privacy',
    'GPG': 'GNU Privacy Guard',
    'OpenPGP': None,
    'S/MIME': 'Secure/Multipurpose Internet Mail Extensions',
    'OAuth': 'Open Authorization',
    'OIDC': 'OpenID Connect',
    'SAML': 'Security Assertion Markup Language',
    'Kerberos': None,
    'LDAP': 'Lightweight Directory Access Protocol',
    'Active Directory': 'Microsoft Active Directory',
    'NTLM': 'New Technology LAN Manager',
    'SSO': 'Single Sign-On',
    'MFA': 'Multi-Factor Authentication',
    '2FA': 'Two-Factor Authentication',
    'TOTP': 'Time-based One-Time Password',
    'HOTP': 'HMAC-based One-Time Password',
    'FIDO2': 'Fast Identity Online 2',
    'WebAuthn': 'Web Authentication',
    'CTAP': 'Client to Authenticator Protocol',
    'PKI': 'Public Key Infrastructure',
    'CA': 'Certificate Authority',
    'CRL': 'Certificate Revocation List',
    'OCSP': 'Online Certificate Status Protocol',
    'CSR': 'Certificate Signing Request',
    'TPM': 'Trusted Platform Module',
    'HSM': 'Hardware Security Module',
    'SE': 'Secure Element',
    'TEE': 'Trusted Execution Environment',
    'SGX': 'Intel Software Guard Extensions',
}

def check_file(fpath, chapter_num):
    """检查单个文件的术语使用问题"""
    with open(fpath, encoding='utf-8') as f:
        content = f.read()
    
    issues = []
    
    # 检查常见英文缩写是否在首次出现时有完整介绍
    for abbr, full in KNOWN_ABBR.items():
        if abbr in content:
            # 找到首次出现位置
            idx = content.find(abbr)
            # 向前看最多200字符，看是否有完整介绍
            context_before = content[max(0, idx-200):idx]
            
            # 检查是否已经有"英文全称"格式的介绍
            has_full_intro = False
            if full:
                # 检查是否包含完整名称或其中关键部分
                key_parts = full.split()
                if any(part.lower() in context_before.lower() for part in key_parts[:2] if len(part) > 3):
                    has_full_intro = True
            
            # 检查是否有"中文（英文，缩写）"格式
            has_paren_format = re.search(r'[（(]' + re.escape(abbr) + r'[）)]', context_before) is not None
            has_chinese_intro = re.search(r'中文|英文|全称|缩写|术语|叫做|称为|即', context_before) is not None
            
            if not has_full_intro and not has_paren_format:
                issues.append({
                    'abbr': abbr,
                    'full': full,
                    'context': content[max(0,idx-50):idx+len(abbr)+20].replace('\n','↵'),
                    'pos': idx,
                    'has_paren': has_paren_format,
                    'has_chinese_intro': has_chinese_intro
                })
    
    return issues

# 扫描所有文件
all_issues = []
for chapter_dir, files in CHAPTER_ORDER:
    for fn in files:
        fpath = os.path.join(BASE, chapter_dir, fn)
        if not os.path.exists(fpath):
            continue
        issues = check_file(fpath, chapter_dir)
        if issues:
            section = fn.replace('.md','')
            all_issues.append((chapter_dir, section, fpath, issues))

print(f"=== 通篇术语检查报告 ===\n")
print(f"扫描了 {sum(1 for _,_,_,i in all_issues for _ in [i]) if all_issues else 0} 个潜在问题\n")

# 按出现频率排序缩写
from collections import Counter
abbr_counts = Counter()
for ch, sec, fp, issues in all_issues:
    for iss in issues:
        abbr_counts[iss['abbr']] += 1

print("=== 高频缩写 TOP 30 ===")
for abbr, cnt in abbr_counts.most_common(30):
    full = KNOWN_ABBR.get(abbr, '?')
    print(f"  {abbr} ({full}): {cnt}处")

print(f"\n=== 详细问题列表 ===")
for ch, sec, fp, issues in all_issues:
    print(f"\n{ch}/{sec}:")
    for iss in issues[:5]:  # 每节最多显示5个
        status = "⚠️ 需补充" if not iss['has_paren'] and not iss['has_chinese_intro'] else "✓ OK"
        print(f"  {status} [{iss['abbr']}] {iss['context'][:80]}")
